# Generated by Django 4.0.6 on 2022-08-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
                ('category_name_ru', models.CharField(max_length=50, null=True, verbose_name='Категория')),
                ('category_name_en', models.CharField(max_length=50, null=True, verbose_name='Категория')),
                ('cat_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('cat_description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('cat_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('premiere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Премьера')),
                ('premiere_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Премьера')),
                ('premiere_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Премьера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=250, verbose_name='Место проведения, Адрес')),
                ('address_ru', models.CharField(max_length=250, null=True, verbose_name='Место проведения, Адрес')),
                ('address_en', models.CharField(max_length=250, null=True, verbose_name='Место проведения, Адрес')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('date_ru', models.DateTimeField(null=True, verbose_name='Дата и время проведения')),
                ('date_en', models.DateTimeField(null=True, verbose_name='Дата и время проведения')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена')),
                ('price_ru', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена')),
                ('price_en', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена')),
                ('contacts', models.CharField(blank=True, max_length=250, null=True, verbose_name='Контакты')),
                ('contacts_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Контакты')),
                ('contacts_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Контакты')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha_app.category', verbose_name='Категория')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha_app.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
    ]
