# Generated by Django 4.0.6 on 2022-08-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='contacts_en',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='contacts_ru',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='date_ru',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='price_ru',
        ),
    ]
